# Generated by Django 5.1.3 on 2024-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
