# Generated by Django 5.1.3 on 2024-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_data', '0002_telegrammessage_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='DISEASE_GROUP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
