# Generated by Django 5.1.3 on 2024-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_data', '0003_telegrammessage_disease_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='ORGAN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
