# Generated by Django 5.1.3 on 2024-11-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_data', '0004_telegrammessage_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='HTML_LINK',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
