# Generated by Django 5.1.3 on 2024-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_data', '0005_telegrammessage_html_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
